---
title: "Within-person cognitive performance across abilities among adversity-exposed people in the SECCYD"
output: md_document
bibliography: references.bib
csl: apa.csl
link-citations: true
editor-options:
  markdown:
    canonical: true
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F, message = F, warning = F)

library(tidyverse)
library(gt)
library(glue)
library(htmltools)
```

*Last updated `r format(Sys.Date(), "%B %d, %Y")`*

## Overview

This repository contains a preregistration, data, code, an (eventual) reproducible manuscript/supplement for a project entitled (working title) "Within-person cognitive performance across abilities among adversity-exposed people in the SECCYD".

This project is a secondary data analysis using the Study of Early Childcare and Youth Development [[SECCYD](https://www.icpsr.umich.edu/web/ICPSR/series/00233), @nichdearlychildcareresearchnetwork2005].

## Directory Structure

The names of each folder are intended to be self-explanatory. There are six top-level folders to organize the inputs and outputs of this project:

1.  [`codebooks/`](codebooks/): lists of variable names, labels, and value labels (where applicable).
2.  `data/`: data, stored as an `.Rdata` file and `.csv` files.
3.  `manuscript/`: a manuscript written in R markdown for submission to a journal.
4.  [`preregistration/`](preregistration/): a preregistration document based on [\@akker2021] that details my plans for this project.
5.  [`scripts/`](scripts/): R-scripts that read, analyze, and produce all outputs.
6.  `supplement/`: a supplemental text with additional information and materials.

## References
