---
format: docx
reference-doc: reference-doc.docx
bibliography: ../references.bib
csl: ../apa.csl
---

# Abstract

\noindent The idea that some skills might be enhanced by adversity is gaining traction. For example, research leveraging the hidden talents approach has uncovered a few narrow, context-dependent skills enhanced by exposure to adversity. Yet, in order for a field to grow, we must not dig too deep, too fast. In this paper, we zoom out and evaluate two basic features of the hidden talents approach. First, adversity simultaneously decreases and increases test performance, depending on the specific skill. Although commonly assumed, this assertion is rarely tested. Second, empirical work suggests that enhanced skills manifest within- not between- individuals. Although studies have compared the same skill in different testing contexts, research comparing different skills have tested only two or three skills. One reason is that the hidden talents approach uses a functional-link approach to understanding which skills fit the challenges of adverse environments. We expand on this finding by analyzing ten skills in the Woodcock Johnson Cognitive and Achievement test battery in a large, prospective longitudinal dataset. Specifically, we use a within-person modeling strategy to examine how exposure to harshness and unpredictability earlier in life are associated with relative decreases and increases in subtest performance compared to a person’s overall performance. Our goal is to document adversity-shaped cognitive profiles, identify possible drivers of lowered overall performance, and map out sets of ‘intact’ skills. 

{{< pagebreak >}}

# Within-person cognitive performance across abilities among adversity-exposed people in the SECCYD

Developmental science commonly asserts that adversity-exposure during development reduces cognitive performance, an assumption built on decades of empirical findings (Duncan et al., 2017; Farah et al., 2006; Hackman et al., 2010, 2014; McLaughlin et al., 2019; Raby et al., 2015). In recent years, however, adaptation-based frameworks, rooted in the idea that adversity might enhance certain abilities, have complimented this work—and it is gaining traction (Ellis et al., 2020; Frankenhuis, Young, et al., 2020; Frankenhuis & de Weerth, 2013; Frankenhuis & Nettle, 2020). Since its inception, the goal of adaptation-based frameworks has been to inspire a more well-rounded view of adversity and its influence on abilities—one that incorporates both the struggles and strengths of people from disadvantaged backgrounds (Frankenhuis & de Weerth, 2013). As it develops, the core task of adaptation-based research is to “uncover a high-resolution map of specific cognitive abilities that are enhanced as a result of growing up under high-adversity conditions” (Ellis et al., 2017, p. 562). 
To illustrate this map, research has used confirmatory study designs, which has gleaned useful insights. Yet, to cultivate growth in an emerging research program—where little is known and there is much to learn—we must not dig too deep, too fast. Without complimentary approaches, exclusive use of confirmatory designs can create tunnel vision and miss new insights. In this paper, we use a complimentary approach to confirmatory research: principled exploration. Our broad goal is to contribute to drawing our map of adversity shaped abilities. To do so, we extract the essential features of adaptation-based research to drive our exploration into new territory and to re-map familiar ground.

# Motivating Principled Exploration

Most adaptation-based research is confirmatory because its core features are useful guideposts for hypothesis generation. For example, adaptation-based perspectives assume development shapes the individual, and their abilities, to fit the local environment (Frankenhuis, Young, et al., 2020). Because environments differ in the challenges they pose, development can shape a variety of abilities according to specific challenges. With these ideas as building blocks, it is easy to construct an intuitive bridge between an ability and an environmental challenge and, therefore, generate reasonably specific hypotheses. For example, a researcher can identify a specific challenge posed by a dimension of adversity (e.g., threats to safety in high crime neighborhoods) and the specific abilities needed to meet those challenges (e.g., heightened vigilance). This approach is appealing because it forces researchers to be specific and logically tie together challenges posed by an environment and abilities that should help people meet them. 

This approach has discovered a handful of interesting adversity-enhanced abilities. For example, past work has proposed that constantly changing environments might shape the ability to track and respond to changing information. Using this logic, studies have found that exposure to more unpredictable environments tend to enhance both attention-shifting and working memory updating, two abilities thought to help deal with changes in the environment (Fields et al., 2021; Mittal et al., 2015; Young et al., 2018). Confirmatory hypotheses have also focused on testing content, the notion that performance should improve when the testing content matches the lived experience of people exposed to adversity. For example, Frankenhuis and colleagues (2020) hypothesized that exposure to violence might enhance reasoning about social dominance hierarchies—but not for neutral content, such as age. Their study revealed that youth exposed to more violence were equally or more accurate when asked to memorize social dominance relationships than youth exposed to less violence. Using a similar experimental paradigm, Young and colleagues (2022) examined how real world compared to abstract testing stimuli affects performance on attention shifting and working memory tests. They found that adversity-exposed youth score higher on working memory updating tasks with real world compared to abstract content.

Adaptation-based, confirmatory approaches are clearly useful, but they also have pitfalls. Emerging research programs have yet to lay basic groundwork for testing theories, such as auxiliary assumptions or boundary conditions (Scheel et al., 2021). This reduces our ability to understand conflicting findings. For example, some studies suggest ecologically relevant testing content enhances performance on executive functions but others find ecological content reduces performance on standardized tests (Duquennois, 2022; Muskens, 2019). Is this because each study tested different types of cognitive abilities, used different ecological content, both, or is there a different explanation entirely? In addition, the logic behind confirmatory studies can easily flipped. For example, inhibition, or the ability to resist distractions, is often thought to be reduced by unpredictable environments. If threats and opportunities arise, it is important to quickly respond to them, rather than focus on a long-term goal. But one could make the exact opposite assertion using adaptive logic. For example, inhibition is adaptive in unpredictable environments because saves energy in an environment when there are constant distractions. The broader point is that confirmatory research might need more information before it can be informative (Scheel et al., 2021).

# The Current Study

We see two reasons for conducting principled exploration in this area. The first is to re-examine established patterns with a new lens. The second is to feed adaptation-based theory with useful description. Our aim, therefore, is to complement adaptation-based, confirmatory research with principled exploration (Flournoy et al., 2020; Rozin, 2001). To return to the map of cognitive skills that might be shaped by adversity, what territory needs exploration and which areas may need re-mapping? Rather than relying on confirmatory hypotheses to guide our approach, let’s consider the essential features of an adaptation-based framework. First, an ability might be enhanced when it helps to meet an environmental challenge, but it should be reduced when it does not. This suggests that adaptation and impairment can exist at the same time within the same person. Although commonly assumed, this assertion is rarely tested. Second, as suggested by recent empirical work, enhanced abilities should be witnessed within rather than between individuals (Fields et al., 2021; Frankenhuis, de Vries, et al., 2020; Young et al., 2022). Although some studies have compared the same ability in different contexts, research comparing different skills have tested no more than two or three abilities (Fields et al., 2021; Mittal et al., 2015; Young et al., 2018). Thus, we need within-person designs that examine cognitive performance across many abilities. 

Finally, research typically focuses on comparing reduced versus enhanced test performance, but some abilities might remain ‘intact’ (unaffected) by exposure to adversity (Frankenhuis, Young, et al., 2020). We know little about the intact skills of people exposed to adversity. We also know little about the drivers of lowered performance on broad and generic measures of ability. Traditional approaches have collapsed many abilities into composites and find that adversity exposure lowers performance (REFS), despite the fact that a smaller set of skills could be driving certain effects. 

In sum, we believe that adaptation-based frameworks can provide useful guideposts, but one should use shovels, not scalpels, when breaking new ground. In this paper, therefore, we focus on developing basic criteria for identifying enhanced, intact, and performance drivers of different cognitive abilities. We apply these criteria to investigate how exposure to harshness and unpredictability in particular shape cognitive profiles across ten cognitive skills. We then explore these skills within-person to examine relative decreases and increases in test performance compared to a person’s overall test performance. Our overarching goal is to excavate new ground, re-map old territory, and fuel theory development. In doing so, we position ourselves to identify the key drivers of lowered overall cognitive performance, map out sets of ‘intact’ cognitive skills, and discover cognitive enhancements. We also hope to encourage adaptation-based researchers to conduct systematic explorations to more accurately draw the map of cognitive skills of people who have been exposed to adversity.
